#!/bin/bash
#See skript näitab kasutaja poolt sisestatud numbrite summat

read -p "Sisesta suvaline täisarv:" arv

summa=0

while [ $arv -ne 0 ]

do

	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))

done

	echo "Nende arvude summa on $summa"
