#!/bin/bash
#See skript tervitab kasutajat olenevalt kellaajast ja loeb kella automaatselt

kell=$(date +%T | cut -c1,2)

if test $kell -ge 6 -a $kell -lt 12 ; then

	echo "Tere hommikust!"

elif test $kell -ge 12 -a $kell -lt 18 ; then

	echo "Tere päevast!"

elif test $kell -ge 18 -a $kell -lt 22 ; then

	echo "Tere õhtust!"

elif test $kell -ge 22 -a $kell -le 24 -o $kell -ge 0 -a $kell -lt 6 ; then

	echo "Head ööd!"

fi
